# TODO: try export examples
# https://stackoverflow.com/questions/41628487/getting-outputs-from-aws-cloudformation-describe-stacks
#
#  STACK=ver7
#
#  aws cloudformation create-stack
#  --stack-name ${STACK}
#  --template-body file://cloud-form.yml
#  --parameters "ParameterKey=KeyName,ParameterValue=MyBeanstalkEc2" "ParameterKey=InstanceType,ParameterValue=t2.micro"
#
# aws cloudformation describe-stacks --stack-name ${STACK}--query 'Stacks[0].Outputs'
#
# aws cloudformation describe-stacks --stack-name ${STACK}--query "Stacks[0].Outputs[?OutputKey=='PublicDNS'].OutputValue" --output text
#
# aws cloudformation delete-stack --stack-name ${STACK}
#
AWSTemplateFormatVersion: '2010-09-09'
Description: Template for starting my EC2
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair like "MyBeanstalkEc2". Cannot be blank.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.nano
    AllowedValues: [t2.nano, t2.micro, t2.small]
    ConstraintDescription: Must be a valid EC2 instance type.
  SSHLocation:
    # This does not quite work. Even with nonsense value like 1.2.3.4/0 one can get in
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be valid IP CIDR range of the form x.x.x.x/x. Default lets in connections from anywhere.
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    Description: 'Which kind of image to get among the ones returned by 
    aws ssm get-parameters-by-path --path "/aws/service/ami-amazon-linux-latest" --region us-east-1'
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref 'SSHLocation'
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, AvailabilityZone]
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicDnsName]
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]
